# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: ad5432fef0aefaa77f2855897de958b8dd0de2ca9b5e8be6e65b5c330b223762e7ed9f271b55de049bd597d1135924cf8fd39cbdbc89be6c0c049b390dd3a077

test:
  domain_name: example.com 
  secret_key_base: 2e3bb13723d34b52508a3d09fea3012b90dac1d6fe002566271d6d995186774c7f028c5bef406337df966798c017f4bdeb9ca01cf9fba49f75f653abb5ce991b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
