# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb85516eb08ea4b167b4de9ff04647cb1d590a99a09e8ccbf19d076402ba36472445d5a5a90250669be5d02d44eeb97b21422267ab3cb7cf1f9ceb5db6f047eb

test:
  secret_key_base: 458d55668e5a2ca1f39956e8f39daf119602ddb5a029036e591494ca9cb756092f377a0b38cfc4c42a1ddb2ec6c171b291a22c2df5bad8ec51acc0044f997433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
